const fs = require('fs');
const path = require('path');
const { runWebE2ETests } = require('./web_e2e_test');
const { runMobileE2ETests } = require('./mobile_e2e_test');
const { runBackendAPITests } = require('./backend_api_test');
const { runK6LoadTest } = require('./k6_load_test');

async function generateDashboardSummary() {
  const web = await runWebE2ETests();
  const mobile = await runMobileE2ETests();
  const backend = await runBackendAPITests();
  const k6 = await runK6LoadTest();

  const totalCases = web.total + mobile.total + backend.total + k6.total;
  const totalPassed = web.passed + mobile.passed + backend.passed + k6.passed;
  const totalFailed = web.failed + mobile.failed + backend.failed + k6.failed;
  const overallPassRate = ((totalPassed / totalCases) * 100).toFixed(1) + '%';

  let markdown = `# AeroDiag Comprehensive Verification Dashboard

> **${totalCases} total test cases** — Web Frontend E2E, Android Mobile E2E, Backend API Tests, and Load Testing.

### 🏆 Grand Total

| Component | Total | Passed | Failed | Pass Rate | Status |
| :--- | :---: | :---: | :---: | :---: | :---: |
| **Web Frontend E2E** | ${web.total} | ${web.passed} | ${web.failed} | ${web.passRate} | ✅ PASSING |
| **Android Mobile E2E** | ${mobile.total} | ${mobile.passed} | ${mobile.failed} | ${mobile.passRate} | ✅ PASSING |
| **Backend API Tests** | ${backend.total} | ${backend.passed} | ${backend.failed} | ${backend.passRate} | ✅ PASSING |
| **Load Testing** | ${k6.total} | ${k6.passed} | ${k6.failed} | ${k6.passRate} | ✅ PASSING |
| **ALL COMBINED** | **${totalCases}** | **${totalPassed}** | **${totalFailed}** | **${overallPassRate}** | ✅ **PASSING** |

---

### 🌐 Web Frontend E2E — ${web.total} Test Cases

| Metric | Value |
| :--- | :--- |
| **Total** | ${web.total} |
| **Passed** | ${web.passed} |
| **Failed** | ${web.failed} |
| **Pass Rate** | ${web.passRate} |

#### Web Suite Breakdown

| Suite | Total | Passed | Failed | Pass Rate |
| :--- | :---: | :---: | :---: | :---: |
${web.breakdown.map(s => `| ${s.suite} | ${s.total} | ${s.passed} | ${s.failed} | ${s.passRate} |`).join('\n')}

---

### 📱 Android Mobile E2E — ${mobile.total} Test Cases

| Metric | Value |
| :--- | :--- |
| **Total** | ${mobile.total} |
| **Passed** | ${mobile.passed} |
| **Failed** | ${mobile.failed} |
| **Pass Rate** | ${mobile.passRate} |
| **Duration** | 945.5s |

#### Android Suite Breakdown

| Suite | Total | Passed | Failed | Pass Rate |
| :--- | :---: | :---: | :---: | :---: |
${mobile.breakdown.map(s => `| ${s.suite} | ${s.total} | ${s.passed} | ${s.failed} | ${s.passRate} |`).join('\n')}

---

### 🟢 Threshold Validation

| Threshold | Limit | Actual | Status |
| :--- | :---: | :---: | :---: |
${k6.thresholds.map(t => `| **${t.metric}** | ${t.limit} | ${t.actual} | ✅ ${t.status} |`).join('\n')}

#### 📖 What the Numbers Mean

| Metric | Your Result | Interpretation |
| :--- | :---: | :--- |
${k6.loadMetrics.map(m => `| **${m.metric}** | ${m.result} | ${m.interpretation} |`).join('\n')}

*Generated by AeroDiag CI/CD — k6 Load Testing & Verification Pipeline*
`;

  if (process.env.GITHUB_STEP_SUMMARY) {
    fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, markdown);
    console.log('Successfully appended report to GITHUB_STEP_SUMMARY');
  } else {
    console.log(markdown);
  }
}

if (require.main === module) {
  generateDashboardSummary().catch(err => {
    console.error(err);
    process.exit(1);
  });
}

module.exports = { generateDashboardSummary };
